### ISSUE TITLE
Support for arbitrary id values

### ISSUE THREAD

**Issue by den1k** [oakes/odoyle-rules#2]
Is there’s a reason ids have to be integers or qualified keywords?

https://github.com/oakes/odoyle-rules/blob/913a7414697e38cc8ba1847f68db8bb3c9633d38/src/odoyle/rules.cljc#L9

I’ve imagined using odoyle-rules with a remote db or frontend framework Where I often end up with either strings or idents, e.g `[remote-db/id “42”]` for ids

**Comment by oakes** [comment]
I wasn't able to come up with a good use case for arbitrary ids, but you make a good point. I'll change the spec to just be `any?` before the next release.

**Comment by oakes** [comment]
Just released 0.5.0 with this change :D
